### ISSUE TITLE
npm dependencies failed to install

### ISSUE THREAD

**Issue by haroonhassan** [explosion/jupyterlab-prodigy#5]
Trying to install...prodigy 1.8 is installed as is JupyterLab...get the following error when I try to install the extension...any help appreciated.

$ jupyter labextension install jupyterlab-prodigy
Building jupyterlab assets
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-8dpjabvf.log

**Comment by ines** [comment]
What version of Jupyterlab do you have installed? Can you double-check you're running v1.0?

**Comment by haroonhassan** [comment]
Hi Ines (btw really enjoyed IRL)...

just double checked it is the 1.0. Here is the Pipefile for the environment:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
prodigy = {path = "/home/haroon/prodigy/whls/prodigy-1.8.3-cp35.cp36.cp37-cp35m.cp36m.cp37m-linux_x86_64.whl"}
jupyter = "*"
jupyterlab = "1.0.0rc0"
spacy = "*"

[requires]
python_version = "3.6"
```
any help appreciated.

**Comment by LegitStack** [comment]
I got the same error with `jupyter labextension install @pyviz/jupyterlab_pyviz` so I don't think its just affecting jupyterlab-prodigy

**Comment by seyuboglu** [comment]
I'm getting this exact error with `jupyter lab build`

**Comment by ZBLGAOXIN** [comment]
I get the same error with
jupyter labextension install jupyterlab-dash@0.1.0-alpha.3

**Comment by byerancy** [comment]
Hi, I encountered this problem when trying `jupyter labextension install @jupyterlab/toc` on Mac OS, and solved by looking into the log file which suggests the following command:
```
npm update check failed
Try running with sudo or get access
to the local update config store via
sudo chown -R $USER:$(id -gn $USER) /Users/your_user_name/.config
```
It worked for me. 
Hope that helps.

**Comment by Calvinxc1** [comment]
I'm getting the same problem here and @byerancy's approach didn't help me. I checked the referenced log file and found this:
`
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v6.13.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error package-json@6.5.0: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.13.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
`
I tried running `node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install` by itself in the terminal and it completed without error.

**Comment by davidrpugh** [comment]
I fixed similar issues by making sure that a relatively recent version of nodejs was installed inside my conda environment.

Try adding...
```
  - nodejs=10.13
```
...to your `environment.yml` file and then re-build your environment. Note that `10.13` is the most recent version of `nodejs` available on the default channels.

**Comment by BlueCog** [comment]
I'm getting the  `RuntimeError: npm dependencies failed to install` error on installing jupyterlab-manager: `jupyter labextension install @jupyter-widgets/jupyterlab-manager@^1.1`

I'm at nodejs version 10.16.3.: `npm info using node@v10.16.3`

I've tried building jupyterlab-manager from source and activating with `jupyter labextension link .` but to no avail.

**Comment by x83443647629** [comment]
I fixed it by delete jupyterlab-plotly extension

**Comment by x83443647629** [comment]
I've had a problem with the plot code in jupyterlab, which doesn't show, and the program doesn't report errors., and i had installed the extension as follows:
fasta-extension: jupyter labextension install @jupyterlab/fasta-extension
geojson-extension: jupyter labextension install @jupyterlab/geojson-extension
katex-extension: jupyter labextension install @jupyterlab/katex-extension
mathjax3-extension: jupyter labextension install @jupyterlab/mathjax3-extension
vega2-extension: jupyter labextension install @jupyterlab/vega2-extension
vega3-extension: jupyter labextension install @jupyterlab/vega3-extension

and my code as follows :
import plotly.graph_objs as go
fig = go.Figure({
    'data':[{'type':'bar',
             'x':[1,2,3],
             'y':[1,3,2]}],
    'layout':{'title':{'text':'A Bar Chart'}}
})
fig.show()

**Comment by PadawanTony** [comment]
I had the same issue. As @davidrpugh said, I fixed it by installing a newer version of node.

If you use conda you can run either `conda install nodejs` or `conda install -c conda-forge nodejs`.

Otherwise, use `n` to install the latest version of node:

    $ [sudo] npm install npm -g
    $ npm install -g n
    $ n latest
    $ n

**Comment by ddouglas87** [comment]
@PadawanTony's [comment](https://github.com/explosion/jupyterlab-prodigy/issues/5#issuecomment-609519793) worked for me.

However, I had to uninstall `conda uninstall -c conda-forge nodejs` first, then do `brew install nodejs`, and then do @PadawanTony's update instructions to get it to work.

I'm not sure why conda was giving me problems, but thankfully there are alternative package managers.

**Comment by iamaziz** [comment]
When I run either `$ jupyter lab build` or `$ jupyter labextension install @jupyter-widgets/jupyterlab-manager`, I get the same error:

```
An error occured.
RuntimeError: npm dependencies failed to install
```

In my case, the error was fixed after I did:
```
brew upgrade node
brew install nodejs
brew link node
```

**Comment by ajdajd** [comment]
In my case, `conda install nodejs` fixed it.

`type nodejs` wasn't returning anything even after installing using `conda install -c conda-forge nodejs`.

**Comment by caracicatrz** [comment]
Neither  the conda install nor the forge works for me.

**Comment by EAly** [comment]
I get the same error when tryin to run ```jupyter lab build```

**Comment by spdavern** [comment]
I got this same error when trying to run `jupyter lab build` while in a created conda environment (not the base conda environment) that had nodejs installed (v. 10.13.0).  I completed these steps:

1. Returned to the base conda environment:  `conda deactivate` 
2. Installed nodejs in the base environment: `conda install nodejs` 
3. Reactivated the created conda environment: `conda activate new_env`
4. `jupyter lab build`

And the new build succeeded.

**Comment by EricCacciavillani** [comment]
Don't have much input besides the fact I have this problem for a long time as well. Very confused about how to fix it. (I did try your suggestions as well; nothing seemed to work for me.)

**Comment by gengyong** [comment]
I meet this issue before, finally I found what caused it on my local environment, I don't sure what happened on your kits,  but you can have a try.

if you installed anaconda with 'just for me' option, the anaconda copy will be installed to your home folder. 
on windows 10,  the Windows Defender Center -> Virus and threat protection will block any access of home folder form 'unknown' application such as 'nodejs', which may cause npm failed.

to fix this issue, just disable it from windows defender center settings, or add the 'nodejs' application to white list.

**Comment by kinglionsz** [comment]
https://github.com/jupyterlab/jupyterlab/pull/8455/commits/f3aa259572ab174229704c0d609643161dff275a

Usage with private NPM registry
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To install extensions, you will need access to a NPM packages registry. Some companies do not allow
reaching directly public registry and have a private registry. To use it, you need to configure ``npm``
and ``yarn`` to point to that registry (ask you corporate IT department for the correct URL):

.. code::

    npm config set registry https://registry.company.com/
    yarn config set registry https://registry.company.com/

JupyterLab will pick up that registry automatically.

.. note::

    You can check which registry URL is used by JupyterLab by running::
    
      python -c "from jupyterlab.commands import AppOptions; print(AppOptions().registry)"

Installation problems
~~~~~~~~~~~~~~~~~~~~~
@@ -182,7 +201,7 @@ which means, SSL communication will not be required for downloading Python libra
Using the tips from above, you can handle many network problems 
related to installing Python libraries.

Many Jupyter extensions require having a working ``npm`` command,
Many Jupyter extensions require having a working ``npm`` and ``jlpm`` (alias for ``yarn``) commands,
which is required for downloading useful Jupyter extensions or other JavaScript ‎依赖‎.

Example of typical error message, when ``npm`` cannot connect to own ‎存储 库‎:
@@ -197,6 +216,7 @@ Example of typical error message, when ``npm`` cannot connect to own repositorie
    # Set default registry for NPM (optional, useful in case if common JavaScript libs cannot be found)

    npm config set registry http://registry.npmjs.org/
    jlpm config set registry https://registry.yarnpkg.com/


fixed this issue! build succeeded!

**Comment by TrubadurOsman** [comment]
I had the same issue. I have tried different versions of nodejs with different environments but couldn't solve the issue. I have checked the log files and found out that there was a problem with yarn cache so clearing the yarn cache solved my problem.
